FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

RUN uv sync --system

EXPOSE 8000

CMD uvicorn server.main:app --host 0.0.0.0 --port $PORT