FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

RUN uv sync 

EXPOSE 8501

CMD streamlit run client/app.py --server.port $PORT --server.address 0.0.0.0
